output_file: docker-compose.yaml

clients:

  - id: 2
    files_path: ./files/long/client_2

workers:
  twentieth_century: 3
  main_movie: 3
  esp_production: 3
  no_colab_productions: 3
  sentiment: 3
  arg_production: 3
  credits: 3
  ratings: 3

test: true