services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10
    volumes:
      - ./rabbitmq/config.ini:/config.ini

  client:
    build:
      context: .
      dockerfile: client/client.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  twentieth_century_arg_production_filter:
    build:
      context: .
      dockerfile: filters/twentieth_century_arg_production/twentieth_century_arg_production_filter.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  twentieth_century_arg_esp_aggregator:
    build:
      context: .
      dockerfile: aggregator/twentieth_century_arg_esp_aggregator/aggregator.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  esp_production_filter:
    build:
      context: .
      dockerfile: filters/esp_production/esp_production_filter.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1


  top_5_countries_filter:
    build:
      context: .
      dockerfile: filters/top_5_local/top_5_local.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  top_5_countries_aggregator:
    build:
      context: .
      dockerfile: aggregator/top_aggregator/aggregator.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  twentieth_century_arg_aggregator:
    build:
      context: .
      dockerfile: aggregator/twentieth_century_arg_aggregator/aggregator.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  credits_joiner:
    build:
      context: .
      dockerfile: joiner/credits/credits_joiner.dockerfile
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
